sudo: true
dist: trusty
language: node_js

node_js:
  - node

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

script:
  - npm run prepare
